- name : install nginx 
  ansible.builtin.dnf:
    name: nginx
    state: present
- name: Enable service httpd, and not touch the state
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started

- name: rm command
  ansible.builtin.command: rm -rf /usr/share/nginx/html/* 

- name: Download foo.conf
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /tmp/frontend.zip

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy file with owner and permissions
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf

- name: Restart service httpd, in all cases
  ansible.builtin.service:
    name: nginx
    state: restarted