- name: Remove directory
  ansible.builtin.file:
    path: "{{ PATH }}"
    state: absent

- name: Create directory
  ansible.builtin.file:
    path: "{{ PATH }}"
    state: directory

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{COMPOUNENT}}-v2.zip"
    dest: "{{ PATH }}"
    remote_src: yes